In [ ]:
a = np.array([1,2,3,4])
print(a)

NameError: name 'np' is not defined

In [ ]:
a + 2

array([3, 4, 5, 6])

In [ ]:
a - 2

array([-1,  0,  1,  2])

In [ ]:
a * 2

array([2, 4, 6, 8])

In [ ]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [ ]:
a ** 2

array([ 1,  4,  9, 16])

In [ ]:
# Take the sin
ary = np.array([0,2,3,4]) #ans in radian
np.cos(ary)

array([ 1.        , -0.41614684, -0.9899925 , -0.65364362])

##### Linear Algebra

The np.matmul(a, b) function performs matrix multiplication between a and b.
For matrix multiplication, the number of columns in the first matrix a must equal the number of rows in the second matrix b.

In [ ]:
import numpy as np

# 2D Matrix Multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
result = np.matmul(A, B)
print("Matrix Multiplication with matmul:\n", result)

Matrix Multiplication with matmul:
 [[19 22]
 [43 50]]


In [ ]:
import numpy as np

# Define 3D arrays
A = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

B = np.array([
    [[9, 10], [11, 12]],
    [[13, 14], [15, 16]],[[3,4],[5,6]]])


print("Array A:\n", A)
print("Array B:\n", B)
# Perform matrix multiplication
result = np.matmul(A, B)

print("Resulting 3D Array:\n", result)


Array A:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Array B:
 [[[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[ 3  4]
  [ 5  6]]]


ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,2,2)->(2,newaxis,newaxis) (3,2,2)->(3,newaxis,newaxis)  and requested shape (2,2)

In [ ]:
#Determinant of a Matrix
C = np.array([[1,2,5],[3,4,8],[8,7,6]])

det = np.linalg.det(C)
print(int(det))

5


In [ ]:
# Find the determinant
c = np.identity(5)
np.linalg.det(c)

1.0

In [ ]:
c = np.full((5,5),[8,7,6,9,4])
print(c)
print(np.linalg.det(c))

[[8 7 6 9 4]
 [8 7 6 9 4]
 [8 7 6 9 4]
 [8 7 6 9 4]
 [8 7 6 9 4]]
0.0


In [ ]:
# Example: Inverse of a Matrix
D = np.array([[1, 2], [3, 4]])
inv = np.linalg.inv(D)
print("Inverse of the Matrix:\n", inv)


Inverse of the Matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
D = np.array([[1, 2], [3, 4]])
E = np.array([5, 6])
print(np.linalg.solve(D,E))


[-4.   4.5]


In [ ]:
np.matmul(np.linalg.inv(D),E)

array([-4. ,  4.5])

##### Statistics

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats, axis =0) # finds minimum value in each column

array([1, 2, 3])

In [ ]:
np.min(stats, axis =1) # finds minimum value in each row

array([1, 4])

In [ ]:
np.max(stats)

6

In [ ]:
np.sum(stats, axis=0) #computes sum for each column

array([5, 7, 9])

In [ ]:
np.sum(stats, axis=1) #compute the sum for each row:

array([ 6, 10])